name: scorecard-workflow-dispatch
on:
  schedule:
    - cron: '0 2 * * *'

# Declare default permissions as read only.
jobs:
  scorecard-workflow-dispatch:
    name: Scorecard ${{ matrix.type }} workflow dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [bash, golang]
    steps:
      - name: "workflow dispatch"
        id: workflow-dispatch
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.SCORECARD_TOKEN }}" \
          -d '{"ref":"dev"}' \
          https://api.github.com/repos/ossf-tests/scorecard-action-non-main-branch/actions/workflows/scorecards-${{ matrix.type }}.yml/dispatches
      - name: "Report failed run"
        if: always() && steps.workflow-dispatch.outcome != 'success'
        uses: actions-ecosystem/action-create-issue@b02a3c1d9d929a5839315bd255e40389f0dab627 #v1
        with:
          github_token: ${{ secrets.SCORECARD_TOKEN }}
          title: "Failing e2e tests - scorecard-workflow-dispatch on ${{ github.repository }}"
          body: |
            Matrix: ${{ toJSON(matrix) }}
            Repo: https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}
            Run: https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}
            Workflow name: ${{ github.workflow }}
            Workflow file: https://github.com/${{ github.repository }}/tree/main/.github/workflows/scorecards-workflow-dispatch.yml
            Branch: ${{ github.ref_name }}
          repo: "ossf/scorecard-action"
          labels: |
            e2e
            automated-tests
