name: scorecard-golang
on:
  workflow_dispatch:
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [ dev ]

# Declare default permissions as read only.

jobs:
  scorecard-golang:
    name: Scorecard Golang
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      actions: read
      contents: read
      id-token: write # needed for keyless signing
    steps:
      - name: "Checkout code"
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        with:
          persist-credentials: false
      - name: "Run analysis"
        uses: ossf/scorecard-action@golang-staging
        with:
          results_file: results.sarif
          results_format: sarif
          # Read-only PAT token. To create it,
          # follow the steps in https://github.com/ossf/scorecard-action#pat-token-creation.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Publish the results to enable scorecard badges. For more details, see
          # https://github.com/ossf/scorecard-action#publishing-results.
          # For private repositories, `publish_results` will automatically be set to `false`,
          # regardless of the value entered here.
          publish_results: true
        ## Upload the results as artifacts (optional).
        #- name: "Upload artifact"
        #  uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        #  with:
        #    name: SARIF file
        #    path: results.sarif
        #    retention-days: 5
  check-golang-run:
    runs-on: ubuntu-latest
    needs: [scorecard-golang]
    if: needs.scorecard-golang.result == 'failure'
    steps:
      - uses: actions-ecosystem/action-create-issue@b02a3c1d9d929a5839315bd255e40389f0dab627 #v1
        with:
          github_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          title: "Failing e2e tests - scorecard-golang on ${{ github.repository }}"
          body: |
            Repo: https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_REF_NAME
            Run: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
            Workflow name: $GITHUB_WORKFLOW
            Workflow file: https://github.com/$GITHUB_REPOSITORY/tree/main/.github/workflows/scorecards-golang.yml
            Trigger: $GITHUB_EVENT_NAME
            Branch: $GITHUB_REF_NAME
          repo: "ossf/scorecard-action"
          labels: |
            e2e
            automated-tests
